name: Check 

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format check
        run: pnpm run format

      - name: Test
        run: pnpm test

      - name: Build storybook
        run: pnpm run build-storybook

      - name: Smoke tests
        run: |
          npx http-server storybook-static --port 6006 --silent
          npx wait-on tcp:127.0.0.1:6006
          pnpm run test-storybook



