name: Vitest Tests 

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: null
  workflow_dispatch: null

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV

      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
          always-auth: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest tests
        run: pnpm exec vitest

      - name: Upload Vitest Report
        if: always() 
        uses: actions/upload-artifact@v3
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30